-- USE OF ALTER CLAUSE 
-- ADD A COLUMN CALLED EMAIL TO THE PERSON TABLE

USE mydatabase;

ALTER Table person
add Email varchar(50);

-- USE OD DROP COMMAND TO DROP THE COLUMN FRON THE TABLE
-- REMOVE THE COLUMN PHONE FROM THE TABLE PERSON

ALTER TABLE person
 drop column phone;